### ISSUE TITLE
Not able to deploy on Heroku

### ISSUE THREAD

**Issue by FacelessHuman** [gokulapap/Reconator#10]
Getting below error after clicking on Deploy button at the end. 

We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by sfbcm** [comment]
I think you have to fork this repo and then it should allow you to get accepted in Heroku.

**Comment by gokulapap** [comment]
Yes fork this repo and also change the url to your forked repo url in that heroku deploy button

**Comment by gokulapap** [comment]
After forking the repo, copy your fork url and place it on the below url and open in the browser to deploy !
https://heroku.com/deploy?template=
{your_forked_repo_url}
