### ISSUE TITLE
Source code violation

### ISSUE THREAD

**Issue by nobiittaaa** [gokulapap/Reconator#12]
while deploying app, it shows source code violates Salesforce acceptable use and external facing service policy. Every input is correct, i checked 5 times. adding screenshot for your ref. @gokulapap 

> 
![Screenshot 2022-05-27 004841](https://user-images.githubusercontent.com/70314133/170561789-adbb7886-94e9-4de2-8c2a-af1a807be5f7.png)

**Comment by gokulapap** [comment]
The heroku has detected my source code as violated so now it can't be deployed from my url !
So the solution is,
1) Fork the repo 
2) copy the link of your forked repo and change it in "app.json" file and "deploy to heroku" button 
3) by doing this you can deploy it ! 

Raise an issue if the error still persists
