### ISSUE TITLE
Im unable to deploy the app

### ISSUE THREAD

**Issue by babyhacker0x7** [gokulapap/Reconator#13]
Heroku is new to me. I believe you should create a video on forking so that new Heroku users can benefit from it.

**Comment by gokulapap** [comment]
Sure will make it soon !

**Comment by hacker0x011** [comment]
Heroku says:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.
you can  fixed it by renaming your repository

**Comment by gokulapap** [comment]
Steps to fork the repo and deploy :

1) click on fork button to fork to your repository
2) then copy the url of your forked repo
(eg. Forked url : https://github.com/{your_username}/Reconator
3) then make changes in two files 
     i) app.json -> edit the repo url with your fork url
    ii) README.md -> add the url in deploy to heroku button
4) then click on deploy button from your repo and it will be deployed !
