### ISSUE TITLE
Error ?

### ISSUE THREAD

**Issue by rintomp** [gokulapap/Reconator#16]
![image](https://user-images.githubusercontent.com/89894914/173683016-6677f94d-e67c-4226-bb65-3ece1b92494e.png)

**Comment by gokulapap** [comment]
See the soltion at #10

**Comment by gokulapap** [comment]
Solution to deploy the Reconator !

1) Fork the repo to your github account 
2) Then copy your forked url
Eg. https://github.com/{your_username}/Reconator

3) Paste the forked url in 2 places one in "app.json" file and other in "deploy to heroku" button which will be in README.md

Then click on the deploy to heroku button in your repo and it will get deployed ! If any issues you can ask here
