### ISSUE TITLE
No other scans running after first successful scan

### ISSUE THREAD

**Issue by notmarshmllow** [gokulapap/Reconator#4]
After I ran first scan, I got notification as well as output properly. But later, my other scans are not running. All targets are queued. Also, not receiving any notifications for further scans after first successful scan.

**Comment by gokulapap** [comment]
That's because i have kept a sleep time of 30 minutes after each scan, so the next process starts after 30 minutes

**Comment by gokulapap** [comment]
Thank you for letting me know about this, this has been fixed by adding 1 minute sleep time, now the next scan starts in 1 minute once current target is scanned !
