### ISSUE TITLE
Not able to see gau/{url}

### ISSUE THREAD

**Issue by SagarDhoot** [gokulapap/Reconator#6]
![image](https://user-images.githubusercontent.com/60604508/155518130-bd39d49f-c3c4-456b-b018-678243d47737.png)

**Comment by gokulapap** [comment]
Even after that you're not able to see reopen this issue !

**Comment by SagarDhoot** [comment]
The error still exists. Its been 5 hours now!!

**Comment by gokulapap** [comment]
Did you get notification on finish of recon ?

**Comment by gokulapap** [comment]
If you didn't receive final notification on finish, then it might have met with some errors, so try adding the target again without www like only add target.com alone and check once !

**Comment by gokulapap** [comment]
If you're still getting error let me know ! I will close the issue after confirming

**Comment by SagarDhoot** [comment]
Well, this is not about notification. I'm telling you that the "gau/{url}" part is not visible to me. It's giving me Internal Server Error

**Comment by gokulapap** [comment]
Yes the result gets updated once after each tool runs on the background, so the path /gau/{url} will be accessed only after the gau tool has been run against your target and it gets saved ! So before its generating the output if you access it will throw this 500 server error !
