### ISSUE TITLE
Merging of Gau results

### ISSUE THREAD

**Issue by SAGEof6iixPATHS** [gokulapap/Reconator#7]
Gau results are getting merged with other gau results...
I scanned veeamgov.com and other domains and I found out that other gau results are getting merged with this domain's results.

**Comment by SAGEof6iixPATHS** [comment]
Here you can use this file to understand it better
[temp.txt](https://github.com/gokulapap/Reconator/files/8152713/temp.txt)

**Comment by gokulapap** [comment]
Will be fixed soon !

**Comment by gokulapap** [comment]
Thanks for reporting this issue, I have used a common file to store the results of gau temporarily that was the reason for this issue, this has been fixed now !
If you come across this issue again, reopen this issue
