### ISSUE TITLE
Scan Queue Not responding.

### ISSUE THREAD

**Issue by graphyhiren** [gokulapap/Reconator#8]
After Putting the site in scan queue it remains same forever does not move for scanning. Please help on this issue.

**Comment by graphyhiren** [comment]
Hello,

I followed the same steps as video but still facing same issue ., when i put the site in scan either it remains in queue or if it moves from queue then it does not shows up in scanned site list. 

request you to take look at this and check. i can share video of the behavior from my system.

**Comment by graphyhiren** [comment]
I have redeployed same multiple times, but still facing the issue.

**Comment by graphyhiren** [comment]
Hey I have got the point now., by looking at the logs in heroku app. looks like there was an issue connecting the telegram bot token. so i have revoked current token and configured again with new one, and its working fine.

thank you.

**Comment by gokulapap** [comment]
Thanks for confirming !
